site_name: JP Trip

repo_name: viagem-jp-docs
repo_url: https://github.com/ArthurFerreiraRodrigues/viagem-jp-docs

site_description: "Viagem com os manos para João Pessoa de 05/03/2024 a 13/03/2024."

edit_uri: ""

theme:
  name: material

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  favicon: stylesheets/assets/favicon.png

  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArthurFerreiraRodrigues/viagem-jp-docs

nav:
  - Home: index.md